config/routes.rb
Rails.application.routes.draw do
resources :kittens
root 'kittens#index'
get 'create' => 'kittens#new'

end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
  validates :name, presence: true
  validates :age, presence: true, numericality: {greater_than: 0, less_than: 100}
  validates :cuteness, presence: true,
             numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
  validates :softness, presence: true,
             numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = 'Kitten created!'
      redirect_to root_path
    else
      flash.now[:error] = 'Error'
      render 'new'
    end
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      flash[:success] = 'Kitten updated!'
      redirect_to @kitten
    else
      flash.now[:error] = 'Error'
      render 'edit'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    if @kitten.destroy
      flash[:success] = 'Kitten deleted!'
      redirect_to root_path
    else
      flash[:error] = 'Error'
      redirect_to root_path
    end
  end

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json {render :json => @kittens}
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json {render :json => @kitten}
    end
  end

  private
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_create_kitten.html.erb
<%= render 'shared/error', object: @kitten %>
<%= form_for @kitten do |f| %>
  <%= f.label 'Name' %>
  <%= f.text_field :name %><br>

  <%= f.label 'Age' %>
  <%= f.text_field :age %><br>

  <%= f.label 'Cuteness' %>
  <%= f.text_field :cuteness %><br>

  <%= f.label 'Softness' %>
  <%= f.text_field :softness %><br>

  <%= f.submit("Submit") %>
<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<h1>Edit kitten</h1>

<%= render 'create_kitten' %>
<%= link_to 'delete', @kitten, method: :delete %>

app/views/kittens/index.html.erb
<ul>
  <% @kittens.each do |kitten| %>
    <li><%=link_to kitten.name, kitten %> <%= link_to 'delete', kitten, method: :delete %></li>
  <% end %>
</ul>

app/views/kittens/new.html.erb
<h1>Create kitten</h1>


<%= render 'create_kitten' %>

app/views/kittens/show.html.erb
<h1>Kittens#show</h1>

Name: <%= @kitten.name %><br>
Age: <%= @kitten.age %><br>
Cuteness: <%= @kitten.cuteness %><br>
Softness: <%= @kitten.softness %><br>

<%= link_to 'edit', edit_kitten_path %>
<%= link_to 'delete', @kitten, method: :delete %>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= link_to 'Create', create_path %>
  </header>
  <div class="content">
    <% flash.each do |key, value| %>
      <div class="flash" ><%= value %></div>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>